import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentacionSidebar: [
    /* {
      type: 'category',
      label: 'Guía del Proyecto',
      items: [{ type: 'autogenerated', dirName: '.' }],
    }, */
    {
      type: 'category',
      label: 'Documentación Técnica (TypeDoc)',
      link: { type: 'generated-index', title: 'Documentación API' },
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
    /* {
      type: 'category',
      label: 'Diagramas',
      items: ['diagramas/flujo-transacciones'],
    } */
  ],
};

export default sidebars;
